"""Docs service — orchestrates manifest loading and all Phase 2 validators."""

from pathlib import Path

from grain.adapters.manifest import load_manifest
from grain.cli.output import CommandResult
from grain.domain.documents import DocumentRecord, build_registry
from grain.domain.errors import ForgeError
from grain.validators.authority_validator import validate_authority
from grain.validators.doc_existence_validator import validate_doc_existence
from grain.validators.manifest_validator import validate_manifest_schema


def validate_docs(root: Path) -> CommandResult:
    """Run all documentation validators against the repository at `root`.

    Steps:
    1. Load docs_manifest.yaml
    2. Validate manifest schema
    3. Build document registry
    4. Validate document existence
    5. Validate authority constraints

    Returns:
        CommandResult with ok=True when all checks pass, ok=False with
        errors populated when any check fails.
    """
    errors: list[str] = []

    # Step 1 — load manifest
    try:
        manifest = load_manifest(root)
    except ForgeError as exc:
        return CommandResult(
            ok=False,
            command="docs validate",
            repo=str(root),
            errors=[exc.message],
        )

    # Step 2 — schema validation
    schema_errors = validate_manifest_schema(manifest)
    errors.extend(schema_errors)

    # Steps 3-5 — only proceed if schema is valid (registry requires well-formed manifest)
    if not schema_errors:
        registry = build_registry(manifest)
        errors.extend(validate_doc_existence(registry, root))
        errors.extend(validate_authority(registry, manifest))

    return CommandResult(
        ok=len(errors) == 0,
        command="docs validate",
        repo=str(root),
        errors=errors,
    )


def generate_index(root: Path, dry_run: bool = False) -> CommandResult:
    """Generate or refresh docs/runtime/docs_index.md from the manifest registry.

    Manifest is the authoritative source. The index is derived output.

    Args:
        root: Repository root path.
        dry_run: If True, return the generated content without writing.

    Returns:
        CommandResult with ok=True on success.
    """
    try:
        manifest = load_manifest(root)
    except ForgeError as exc:
        return CommandResult(
            ok=False,
            command="docs index",
            repo=str(root),
            errors=[exc.message],
        )

    registry = build_registry(manifest)
    authority_order = manifest.get("rules", {}).get("authority_order", [])

    lines: list[str] = []
    lines.append("# Docs Index")
    lines.append("")
    lines.append("> Generated by `grain docs index` from `docs/runtime/docs_manifest.yaml`.")
    lines.append("> Do not edit manually — rerun `grain docs index` to refresh.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Authority Order")
    lines.append("")
    for i, entry in enumerate(authority_order, 1):
        lines.append(f"{i}. `{entry}`")
    lines.append("")
    lines.append("---")
    lines.append("")

    for layer in ("canonical", "working", "runtime"):
        records = registry.by_layer(layer)
        if not records:
            continue
        lines.append(f"## {layer.capitalize()} Docs")
        lines.append("")
        lines.append("| ID | Path | Authority | Editable by Agents | Purpose |")
        lines.append("|----|----|----|----|-----|")
        for r in records:
            lines.append(
                f"| `{r.id}` | `{r.path}` | {r.authority} "
                f"| {'yes' if r.editable_by_agents else 'no'} | {r.purpose} |"
            )
        lines.append("")

    content = "\n".join(lines)
    index_path = root / "docs" / "runtime" / "docs_index.md"

    if dry_run:
        return CommandResult(
            ok=True,
            command="docs index",
            repo=str(root),
            warnings=[f"dry-run: would write {len(lines)} lines to {index_path}"],
        )

    index_path.write_text(content, encoding="utf-8")
    return CommandResult(
        ok=True,
        command="docs index",
        repo=str(root),
        files_updated=[str(index_path.relative_to(root))],
    )


def show_doc(root: Path, doc_id: str) -> tuple[CommandResult, DocumentRecord | None]:
    """Look up a single document by ID from the manifest registry.

    Returns a tuple of (CommandResult, DocumentRecord | None).
    CommandResult.ok is False when the manifest cannot be loaded or the doc
    is not found. The record is None on failure.
    """
    try:
        manifest = load_manifest(root)
    except ForgeError as exc:
        return CommandResult(
            ok=False,
            command="docs show",
            repo=str(root),
            errors=[exc.message],
        ), None

    registry = build_registry(manifest)
    record = registry.by_id(doc_id)

    if record is None:
        return CommandResult(
            ok=False,
            command="docs show",
            repo=str(root),
            errors=[f"Doc '{doc_id}' not found in manifest"],
        ), None

    return CommandResult(
        ok=True,
        command="docs show",
        repo=str(root),
    ), record
