"""Draft document generator for existing-project onboarding."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from grain.domain.scan_result import ScanResult


@dataclass
class OnboardDocManifest:
    """Manifest of generated/unchanged files for onboarding drafts."""

    root: str
    created: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)


class OnboardDocGenerator:
    """Generate additive draft docs from scan signals."""

    def __init__(self, root: Path):
        self.root = root

    def generate(self, scan: ScanResult, *, dry_run: bool = False) -> OnboardDocManifest:
        manifest = OnboardDocManifest(root=str(self.root.resolve()))
        docs = self._build_docs(scan)

        for rel, content in docs.items():
            target = self.root / rel
            if target.exists():
                manifest.skipped.append(rel)
                continue
            manifest.created.append(rel)
            if not dry_run:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(content, encoding="utf-8")

        return manifest

    def _build_docs(self, scan: ScanResult) -> dict[str, str]:
        return {
            "docs/canonical/product_scope.md": self._product_scope_draft(scan),
            "docs/canonical/architecture.md": self._architecture_draft(scan),
            "docs/working/backlog.md": self._backlog_draft(scan),
            "docs/working/open_questions.md": self._open_questions_draft(scan),
        }

    def _product_scope_draft(self, scan: ScanResult) -> str:
        languages = ", ".join(scan.primary_languages) if scan.primary_languages else "unknown"
        adapters = ", ".join(scan.applicable_adapters) if scan.applicable_adapters else "none detected"

        return (
            "# Product Scope\n\n"
            "# DRAFT - generated by OnboardDocGenerator; replace with real content\n\n"
            "## Detected Signals\n"
            f"- Primary languages: {languages}\n"
            f"- Applicable adapters: {adapters}\n"
            f"- Key files detected: {len(scan.key_files)}\n"
            f"- CI configs detected: {len(scan.ci_configs)}\n"
            f"- Documentation files detected: {len(scan.documentation_files)}\n\n"
            "## Draft Notes\n"
            "- Confirm product goals and non-goals from maintainers.\n"
            "- Confirm target user and operating constraints.\n"
        )

    def _architecture_draft(self, scan: ScanResult) -> str:
        adapters = ", ".join(scan.applicable_adapters) if scan.applicable_adapters else "none detected"
        key_files = "\n".join(f"- `{path}`" for path in scan.key_files) or "- none detected"
        ci_files = "\n".join(f"- `{path}`" for path in scan.ci_configs) or "- none detected"

        return (
            "# Architecture\n\n"
            "# DRAFT - generated by OnboardDocGenerator; replace with real content\n\n"
            "## Detected Runtime Shape\n"
            f"- Adapter signals: {adapters}\n\n"
            "## Key Files\n"
            f"{key_files}\n\n"
            "## CI Signals\n"
            f"{ci_files}\n\n"
            "## Draft Notes\n"
            "- Validate subsystem boundaries and integration points.\n"
            "- Confirm test strategy and release flow.\n"
        )

    def _backlog_draft(self, scan: ScanResult) -> str:
        return (
            "# Backlog\n\n"
            "# DRAFT - generated by OnboardDocGenerator; replace with real content\n\n"
            "## Adoption Baseline Tasks\n"
            "1. Validate draft canonical docs against maintainers' intent.\n"
            "2. Fill missing architecture decisions from existing system behavior.\n"
            "3. Close open questions and convert accepted decisions into task packets.\n\n"
            "## Scan Snapshot\n"
            f"- Languages: {', '.join(scan.primary_languages) if scan.primary_languages else 'unknown'}\n"
            f"- Adapters: {', '.join(scan.applicable_adapters) if scan.applicable_adapters else 'none detected'}\n"
        )

    def _open_questions_draft(self, scan: ScanResult) -> str:
        questions: list[str] = []

        if not scan.documentation_files:
            questions.append(
                "### Q1 — No documentation detected; what is the authoritative source for project intent?"
            )
        if not scan.ci_configs:
            questions.append("### Q2 — No CI config detected; what verification gate is required before merge?")
        if not any("test" in path.lower() for path in scan.key_files):
            questions.append(
                "### Q3 — Test entrypoints are unclear; which commands should be treated as canonical validation?"
            )
        if not scan.applicable_adapters:
            questions.append("### Q4 — No adapter signals detected; what primary adapter should this project use?")

        for hint in scan.custom_adapter_hints:
            q_num = len(questions) + 1
            questions.append(
                f"### Q{q_num} — Custom adapter suggested\n"
                f"* **Signal:** {hint}"
            )

        if not questions:
            questions.append("### Q1 — Which detected draft assumptions should be corrected first by maintainers?")

        body = "\n\n".join(
            (
                f"{title}\n"
                "* **Status:** decision_needed\n"
                "* **Notes:** DRAFT placeholder generated from repo scan; maintainer input required."
            )
            for title in questions
        )

        return (
            "# Open Questions\n\n"
            "# DRAFT - generated by OnboardDocGenerator; replace with real content\n\n"
            "## Generated Questions\n\n"
            f"{body}\n"
        )

