# SPDX-FileCopyrightText: 2024-2026 Shaznay Sison
# SPDX-License-Identifier: AGPL-3.0-only

"""Draft document generator for existing-project onboarding."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from grain.domain.scan_result import ScanResult

_DRAFT_MARKER = "<!-- DRAFT — generated by grain onboard from existing repo content. Review before treating as canonical. -->"


@dataclass
class OnboardDocManifest:
    """Manifest of generated/unchanged files for onboarding drafts."""

    root: str
    created: list[str] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)


class OnboardDocGenerator:
    """Generate additive draft docs from scan signals."""

    def __init__(self, root: Path):
        self.root = root

    def generate(self, scan: ScanResult, *, dry_run: bool = False) -> OnboardDocManifest:
        manifest = OnboardDocManifest(root=str(self.root.resolve()))
        docs = self._build_docs(scan)

        for rel, content in docs.items():
            target = self.root / rel
            if target.exists():
                manifest.skipped.append(rel)
                continue
            manifest.created.append(rel)
            if not dry_run:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(content, encoding="utf-8")

        return manifest

    def _build_docs(self, scan: ScanResult) -> dict[str, str]:
        return {
            "docs/canonical/product_scope.md": self._product_scope_draft(scan),
            "docs/canonical/architecture.md": self._architecture_draft(scan),
            "docs/working/backlog.md": self._backlog_draft(scan),
            "docs/working/open_questions.md": self._open_questions_draft(scan),
        }

    def _product_scope_draft(self, scan: ScanResult) -> str:
        languages = ", ".join(scan.primary_languages) if scan.primary_languages else "unknown"
        adapters = ", ".join(scan.applicable_adapters) if scan.applicable_adapters else "none detected"

        sections: list[str] = [
            "# Product Scope\n",
            "<!-- DRAFT — generated by grain onboard from existing repo content. Review before treating as canonical. -->\n",
        ]

        # Pull in README or scope doc content if available
        readme_content = self._find_content(scan, {"readme.md", "readme.rst", "readme.txt", "readme"})
        scope_content = self._find_content(scan, {"product_scope.md", "scope.md", "vision.md"})
        pkg_content = scan.existing_doc_content.get("package.json") or scan.existing_doc_content.get("pyproject.toml")

        if pkg_content:
            sections.append(f"## Project Identity\n\n```\n{pkg_content}\n```\n")

        if readme_content:
            sections.append(f"## From README\n\n{readme_content}\n")
        elif scope_content:
            sections.append(f"## From Existing Scope Doc\n\n{scope_content}\n")
        else:
            sections.append(
                "## Purpose\n\n"
                "[No README or scope doc found — fill in: what does this project do and why does it exist?]\n"
            )

        sections.append(
            "## Detected Signals\n\n"
            f"- Primary languages: {languages}\n"
            f"- Applicable adapters: {adapters}\n"
            f"- Key files: {', '.join(f'`{f}`' for f in scan.key_files) or 'none detected'}\n"
            f"- CI configs: {', '.join(f'`{f}`' for f in scan.ci_configs) or 'none detected'}\n\n"
            "## Draft Notes\n\n"
            "- Confirm product goals and non-goals with maintainers.\n"
            "- Confirm target user and operating constraints.\n"
            "- Replace or remove sections that don't apply.\n"
        )

        return "\n".join(sections)

    def _architecture_draft(self, scan: ScanResult) -> str:
        adapters = ", ".join(scan.applicable_adapters) if scan.applicable_adapters else "none detected"
        key_files = "\n".join(f"- `{path}`" for path in scan.key_files) or "- none detected"
        ci_files = "\n".join(f"- `{path}`" for path in scan.ci_configs) or "- none detected"

        sections: list[str] = [
            "# Architecture\n",
            "<!-- DRAFT — generated by grain onboard from existing repo content. Review before treating as canonical. -->\n",
        ]

        arch_content = self._find_content(
            scan, {"architecture.md", "architecture.rst", "design.md", "docs/architecture.md", "docs/design.md"}
        )

        if arch_content:
            sections.append(f"## From Existing Architecture Doc\n\n{arch_content}\n")
        else:
            sections.append(
                "## Overview\n\n"
                "[No architecture doc found — fill in: key subsystems, interfaces, and design decisions.]\n"
            )

        sections.append(
            "## Detected Runtime Shape\n\n"
            f"- Adapter signals: {adapters}\n\n"
            "## Key Files\n\n"
            f"{key_files}\n\n"
            "## CI Signals\n\n"
            f"{ci_files}\n\n"
            "## Draft Notes\n\n"
            "- Validate subsystem boundaries and integration points.\n"
            "- Confirm test strategy and release flow.\n"
            "- Replace or remove sections that don't apply.\n"
        )

        return "\n".join(sections)

    def _find_content(self, scan: ScanResult, names: set[str]) -> str:
        """Return the first matching content from existing_doc_content by filename."""
        for rel, content in scan.existing_doc_content.items():
            if rel.lower() in names or Path(rel).name.lower() in names:
                return content
        return ""

    def _backlog_draft(self, scan: ScanResult) -> str:
        sections: list[str] = [
            "# Backlog\n\n"
            "<!-- DRAFT — generated by grain onboard from existing repo content. Review before treating as canonical. -->\n\n"
            "## Adoption Baseline Tasks\n"
            "1. Validate draft canonical docs against maintainers' intent.\n"
            "2. Fill missing architecture decisions from existing system behavior.\n"
            "3. Close open questions and convert accepted decisions into task packets.\n\n"
            "## Scan Snapshot\n"
            f"- Languages: {', '.join(scan.primary_languages) if scan.primary_languages else 'unknown'}\n"
            f"- Adapters: {', '.join(scan.applicable_adapters) if scan.applicable_adapters else 'none detected'}\n"
        ]

        if scan.detected_modules:
            module_list = "\n".join(f"- `{m}`" for m in scan.detected_modules)
            sections.append(
                "\n## Retrospective Review Required\n\n"
                "> **Warning:** The scanner found existing code modules in this repo. "
                "The backlog above was generated from scratch and may not reflect work already done. "
                "Audit each module below before treating any backlog item as 'not yet built'.\n\n"
                "### Detected Code Modules\n\n"
                f"{module_list}\n\n"
                "### Suggested Audit Steps\n\n"
                "1. For each module, review existing functionality against open backlog items.\n"
                "2. Mark already-completed items as `done` or remove them from the backlog.\n"
                "3. Identify any functionality that exists in code but has no corresponding backlog item.\n"
                "4. Update `docs/canonical/architecture.md` to reflect the actual current state.\n"
            )

        return "".join(sections)

    def _open_questions_draft(self, scan: ScanResult) -> str:
        questions: list[str] = []

        if not scan.documentation_files:
            questions.append(
                "### Q1 — No documentation detected; what is the authoritative source for project intent?"
            )
        if not scan.ci_configs:
            questions.append("### Q2 — No CI config detected; what verification gate is required before merge?")
        if not any("test" in path.lower() for path in scan.key_files):
            questions.append(
                "### Q3 — Test entrypoints are unclear; which commands should be treated as canonical validation?"
            )
        if not scan.applicable_adapters:
            questions.append("### Q4 — No adapter signals detected; what primary adapter should this project use?")

        if scan.detected_modules:
            module_names = ", ".join(f"`{m}`" for m in scan.detected_modules)
            q_num = len(questions) + 1
            questions.append(
                f"### Q{q_num} — Existing code detected; backlog may not reflect current state\n"
                f"* **Modules found:** {module_names}\n"
                f"* **Risk:** Backlog items may already be fully or partially implemented. "
                f"Treat the generated backlog as a starting point only — audit each module before adding work.\n"
                f"* **Action:** Compare detected modules against backlog tasks and mark completed items as `done`."
            )

        for hint in scan.custom_adapter_hints:
            q_num = len(questions) + 1
            questions.append(
                f"### Q{q_num} — Custom adapter suggested\n"
                f"* **Signal:** {hint}"
            )

        # Surface existing docs that were found but not yet in the canonical layer
        if scan.existing_doc_content:
            found = ", ".join(f"`{rel}`" for rel in scan.existing_doc_content)
            q_num = len(questions) + 1
            questions.append(
                f"### Q{q_num} — Existing docs found outside canonical layer\n"
                f"* **Found:** {found}\n"
                f"* **Action:** Review these files and incorporate relevant content into "
                f"`docs/canonical/product_scope.md` and `docs/canonical/architecture.md`."
            )

        if not questions:
            questions.append("### Q1 — Which detected draft assumptions should be corrected first by maintainers?")

        entries: list[str] = []
        for title in questions:
            # Pre-formatted questions already have bullet metadata — don't wrap them
            if any(marker in title for marker in ("* **Status:**", "* **Found:**", "* **Modules found:**", "* **Signal:**", "* **Risk:**")):
                entries.append(title)
            else:
                entries.append(
                    f"{title}\n"
                    "* **Status:** decision_needed\n"
                    "* **Notes:** DRAFT placeholder generated from repo scan; maintainer input required."
                )
        body = "\n\n".join(entries)

        return (
            "# Open Questions\n\n"
            f"{_DRAFT_MARKER}\n\n"
            "## Generated Questions\n\n"
            f"{body}\n"
        )

